### ISSUE TITLE
invalid setup instructions for manifest.json : li.lightningtools.core -> li.lightingtools.lightprobesvolumes

### ISSUE THREAD

**Issue by kendemu** [laurenth-personal/LightingTools.LightProbesVolumes#1]
Hi, 

I read your setup instructions, however I had a error resolving the packages.
I read the package.json profile, and the true package name is li.lightingtools.lightprobesvolumes.

**Comment by davidrochin** [comment]
I can confirm. Instructions need to be updated

**Comment by crogersarvr** [comment]
still same issue.
i added this to manifest.json:
"li.lightingtools.lightprobesvolumes": "file:../LocalPackages/LightingTools.LightProbesVolumes"

**Comment by Ruuubickk** [comment]
Still an issue ^

**Comment by Theformand** [comment]
For future reference: You can inspect the Package.json to figure out what the internal package name is. In this case its "li.lightingtools.lightprobesvolumes" - So all you need to do is add this line to your manifest.json (instead of what the instructions say to add) - "li.lightingtools.lightprobesvolumes": "file:../LocalPackages/LightingTools.LightProbesVolumes"

**Comment by laurenth-personal** [comment]
Sorry I seem to have missed this issue. I just fixed this and made it a package on openUPM which should simplify the setup https://openupm.com/packages/com.laurenth.lightingtools-lightprobesvolumes/
